title: [Assistant Professor Michael Nutt]
description: [My personal website that holds details on projects I've worked on, documents I find useful, and other great online resources.]

# Themes:
# 
# 
# Remote Themes:
# 
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one